<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\CompanyCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/CompanyCommand.php';
include_once $this->targetDirs[3].'/src/Service/CompanyCommandService.php';

$this->privates['App\\Command\\CompanyCommand'] = $instance = new \App\Command\CompanyCommand(new \App\Service\CompanyCommandService(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService())));

$instance->setName('company:employee');

return $instance;
